### ISSUE TITLE
User agent isn't parsed correctly 

### ISSUE THREAD

**Issue by alshakero** [elsigh/browserscope#10]
UA String:
```sh
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
```
UA:
**Chrome 52.0.2743**

Screenshot:
![image](https://user-images.githubusercontent.com/17054134/28470636-9761b5c4-6e3a-11e7-984c-f80a47c8068b.png)

**Comment by easyaspi314** [comment]
Confirmed. Updating Closure should fix the issue.
