### ISSUE TITLE
Top browser listed chrome 32 to be number 1 on the list

### ISSUE THREAD

**Issue by yukinying** [elsigh/browserscope#3]
Is that intentional? Latest version of chrome is 50 now.

**Comment by corvae** [comment]
Also, firefox 26 is listed, but current version is 46 (not including dev releases).  Can this be changed to reflect current versions under Top browser?

**Comment by elsigh** [comment]
It totally can. Would you want to do the pull request by chance? It's not
that obvious how to do it, which I'm sorry about, but I won't have much
time for a while.

**Comment by corvae** [comment]
It looks like you update the versions in models/result_stats.py, but does this have to be updated every time a new version comes out? 

 I tried looking for a maintained list out there somewhere that you could load them from, but I can't find one at the moment.

**Comment by elsigh** [comment]
Yeah, hey Albert! We don't have any better mechanism. I'm landing an update today fwiw.
